### ISSUE TITLE
`iltorb` is deprecated

### ISSUE THREAD

**Issue by boris-petrov** [myfreeweb/broccoli-brotli#3]
`iltorb` is [deprecated](https://github.com/nstepien/iltorb/issues/119#issuecomment-762180705) and the owner suggests using the official Node [API](https://nodejs.org/dist/latest-v15.x/docs/api/zlib.html#zlib_zlib_createbrotlicompress_options).

**Comment by valpackett** [comment]
Would you like to make a pull request doing that? :)
